/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphical;

/**
 *
 * @author lenovo
 */
public class EverythingFruitfulDrinks extends javax.swing.JFrame {

    /**
     * Creates new form EverythingFruitfulDrinks
     */
    public EverythingFruitfulDrinks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dairyMilkButton = new javax.swing.JButton();
        strawberryButton = new javax.swing.JButton();
        chocolateMilkshakeButton = new javax.swing.JButton();
        mangoButton = new javax.swing.JButton();
        galaticButton = new javax.swing.JButton();
        wizardButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mediumCupButton = new javax.swing.JButton();
        galaticButton1 = new javax.swing.JButton();
        mediumCupButton1 = new javax.swing.JButton();
        mediumCupButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 192, 203));

        jPanel2.setBackground(new java.awt.Color(218, 192, 203));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 80, 148));
        jLabel2.setText("Everything Fruitful Cocktails Menu");

        dairyMilkButton.setBackground(new java.awt.Color(218, 192, 203));
        dairyMilkButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dairyMilkButton.setForeground(new java.awt.Color(69, 66, 66));
        dairyMilkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/fruitful_resized_resized.png"))); // NOI18N
        dairyMilkButton.setText("• Fruitful Drink (Our Special)");
        dairyMilkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dairyMilkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dairyMilkButtonActionPerformed(evt);
            }
        });

        strawberryButton.setBackground(new java.awt.Color(218, 192, 203));
        strawberryButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        strawberryButton.setForeground(new java.awt.Color(69, 66, 66));
        strawberryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/strawberry_resized.png"))); // NOI18N
        strawberryButton.setText("• Strawberry Milkshake");
        strawberryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        strawberryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryButtonActionPerformed(evt);
            }
        });

        chocolateMilkshakeButton.setBackground(new java.awt.Color(218, 192, 203));
        chocolateMilkshakeButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        chocolateMilkshakeButton.setForeground(new java.awt.Color(69, 66, 66));
        chocolateMilkshakeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/chocolate_resized.png"))); // NOI18N
        chocolateMilkshakeButton.setText("• Chocolate Milkshake");
        chocolateMilkshakeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chocolateMilkshakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateMilkshakeButtonActionPerformed(evt);
            }
        });

        mangoButton.setBackground(new java.awt.Color(218, 192, 203));
        mangoButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mangoButton.setForeground(new java.awt.Color(69, 66, 66));
        mangoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/mango_resized.png"))); // NOI18N
        mangoButton.setText("• Mango Smoothie");
        mangoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mangoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangoButtonActionPerformed(evt);
            }
        });

        galaticButton.setBackground(new java.awt.Color(218, 192, 203));
        galaticButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        galaticButton.setForeground(new java.awt.Color(69, 66, 66));
        galaticButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/galaxy_resized.png"))); // NOI18N
        galaticButton.setText("• Galatic Mix");
        galaticButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        galaticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galaticButtonActionPerformed(evt);
            }
        });

        wizardButton.setBackground(new java.awt.Color(218, 192, 203));
        wizardButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        wizardButton.setForeground(new java.awt.Color(69, 66, 66));
        wizardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/wizard_resized_1.png"))); // NOI18N
        wizardButton.setText("• Wizard Brew");
        wizardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        wizardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 80, 148));
        jLabel7.setText("Cup Size:");

        mediumCupButton.setBackground(new java.awt.Color(218, 192, 203));
        mediumCupButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mediumCupButton.setForeground(new java.awt.Color(69, 66, 66));
        mediumCupButton.setText("• Medium Cup");
        mediumCupButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumCupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mediumCupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCupButtonActionPerformed(evt);
            }
        });

        galaticButton1.setBackground(new java.awt.Color(218, 192, 203));
        galaticButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        galaticButton1.setForeground(new java.awt.Color(69, 66, 66));
        galaticButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/vanilla_resized.png"))); // NOI18N
        galaticButton1.setText("• Vanilla Shake");
        galaticButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        galaticButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galaticButton1ActionPerformed(evt);
            }
        });

        mediumCupButton1.setBackground(new java.awt.Color(218, 192, 203));
        mediumCupButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mediumCupButton1.setForeground(new java.awt.Color(69, 66, 66));
        mediumCupButton1.setText("• Large Cup");
        mediumCupButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumCupButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mediumCupButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCupButton1ActionPerformed(evt);
            }
        });

        mediumCupButton2.setBackground(new java.awt.Color(218, 192, 203));
        mediumCupButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mediumCupButton2.setForeground(new java.awt.Color(69, 66, 66));
        mediumCupButton2.setText("• Small Cup");
        mediumCupButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumCupButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mediumCupButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCupButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(galaticButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel7)))
                        .addGap(242, 242, 242))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wizardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mangoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dairyMilkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strawberryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chocolateMilkshakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(galaticButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(mediumCupButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mediumCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mediumCupButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dairyMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strawberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mangoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chocolateMilkshakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wizardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(galaticButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(galaticButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumCupButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumCupButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dairyMilkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dairyMilkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dairyMilkButtonActionPerformed

    private void strawberryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strawberryButtonActionPerformed

    private void chocolateMilkshakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateMilkshakeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chocolateMilkshakeButtonActionPerformed

    private void mangoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mangoButtonActionPerformed

    private void galaticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galaticButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_galaticButtonActionPerformed

    private void wizardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wizardButtonActionPerformed

    private void mediumCupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumCupButtonActionPerformed

    private void galaticButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galaticButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_galaticButton1ActionPerformed

    private void mediumCupButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCupButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumCupButton1ActionPerformed

    private void mediumCupButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCupButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumCupButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EverythingFruitfulDrinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EverythingFruitfulDrinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EverythingFruitfulDrinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EverythingFruitfulDrinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EverythingFruitfulDrinks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chocolateMilkshakeButton;
    private javax.swing.JButton dairyMilkButton;
    private javax.swing.JButton galaticButton;
    private javax.swing.JButton galaticButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mangoButton;
    private javax.swing.JButton mediumCupButton;
    private javax.swing.JButton mediumCupButton1;
    private javax.swing.JButton mediumCupButton2;
    private javax.swing.JButton strawberryButton;
    private javax.swing.JButton wizardButton;
    // End of variables declaration//GEN-END:variables
}
