/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphical;

import containers.Blender;
import exceptions.BlenderOverFlowException;
import fruits.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lenovo
 */
public class FruitsMenu extends javax.swing.JFrame {
    
    private Blender blender;

    /**
     * Creates new form FruitsMenu
     */
    public FruitsMenu() {
        initComponents();
        blender =new Blender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        strawberrybuttonGroup = new javax.swing.ButtonGroup();
        appleButtonGroup = new javax.swing.ButtonGroup();
        watermelonButtonGroup = new javax.swing.ButtonGroup();
        blueberryButtonGroup = new javax.swing.ButtonGroup();
        datesButtonGroup = new javax.swing.ButtonGroup();
        orangeButtonGroup = new javax.swing.ButtonGroup();
        PineappleButtonGroup = new javax.swing.ButtonGroup();
        bananaButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        OrangeSRB = new javax.swing.JRadioButton();
        PineappleSRB = new javax.swing.JRadioButton();
        BananaSRB = new javax.swing.JRadioButton();
        MangoSRB = new javax.swing.JRadioButton();
        GrapefruitSRB = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        OrangeNRB = new javax.swing.JRadioButton();
        PineappleNRB = new javax.swing.JRadioButton();
        BananaNRB = new javax.swing.JRadioButton();
        MangoNRB = new javax.swing.JRadioButton();
        GrapefruitNRB = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        OrangeERB = new javax.swing.JRadioButton();
        PineappleERB = new javax.swing.JRadioButton();
        BananaERB = new javax.swing.JRadioButton();
        MangoERB = new javax.swing.JRadioButton();
        GrapefruitERB = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        strawberrySmallRadioButton = new javax.swing.JRadioButton();
        AppleSmallRadioButton1 = new javax.swing.JRadioButton();
        WatermelonSmallRB = new javax.swing.JRadioButton();
        BlueberrySRB = new javax.swing.JRadioButton();
        DatesSRB = new javax.swing.JRadioButton();
        RoseberrySRB = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        strawberryNormalRadioButton14 = new javax.swing.JRadioButton();
        AppleNormalRadioButton15 = new javax.swing.JRadioButton();
        WatermelonNormalRB = new javax.swing.JRadioButton();
        BlueberryNRB = new javax.swing.JRadioButton();
        DatesNRB = new javax.swing.JRadioButton();
        RoseberryNRB = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        strawberryExtraRadioButton20 = new javax.swing.JRadioButton();
        AppleExtraRB = new javax.swing.JRadioButton();
        WatermelonExtraRB = new javax.swing.JRadioButton();
        BlueberryERB = new javax.swing.JRadioButton();
        DatesERB = new javax.swing.JRadioButton();
        RoseberryERB = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 192, 203));

        jPanel2.setBackground(new java.awt.Color(218, 192, 203));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 80, 148));
        jLabel2.setText("Fruits Menu");

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("Strawberry");

        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton35ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(218, 192, 203));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/strawberryIcon.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/appleIcon.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/watermelon.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/blueberry.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/dates.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/roseberry.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(218, 192, 203));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Small");

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Normall");

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Extra");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(218, 192, 203));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Strawberry");

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 51));
        jLabel28.setText("Apples");

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Watermelon");

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Blueberry");

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("Dates");

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("Roseberry");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel28)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(26, 26, 26)
                .addComponent(jLabel28)
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addGap(34, 34, 34)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(33, 33, 33)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(218, 192, 203));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(218, 192, 203));

        jLabel32.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 51));
        jLabel32.setText("Small");

        jLabel33.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 51));
        jLabel33.setText("Normall");

        jLabel34.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 51));
        jLabel34.setText("Extra");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(218, 192, 203));

        jPanel13.setBackground(new java.awt.Color(218, 192, 203));

        orangeButtonGroup.add(OrangeSRB);

        PineappleButtonGroup.add(PineappleSRB);

        bananaButtonGroup.add(BananaSRB);

        strawberrybuttonGroup.add(MangoSRB);
        MangoSRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangoSRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(GrapefruitSRB);
        GrapefruitSRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrapefruitSRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrangeSRB)
                    .addComponent(PineappleSRB)
                    .addComponent(BananaSRB)
                    .addComponent(MangoSRB)
                    .addComponent(GrapefruitSRB))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrangeSRB)
                .addGap(27, 27, 27)
                .addComponent(PineappleSRB)
                .addGap(26, 26, 26)
                .addComponent(BananaSRB)
                .addGap(28, 28, 28)
                .addComponent(MangoSRB)
                .addGap(28, 28, 28)
                .addComponent(GrapefruitSRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(218, 192, 203));

        orangeButtonGroup.add(OrangeNRB);

        PineappleButtonGroup.add(PineappleNRB);

        bananaButtonGroup.add(BananaNRB);

        strawberrybuttonGroup.add(MangoNRB);
        MangoNRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangoNRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(GrapefruitNRB);
        GrapefruitNRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrapefruitNRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrangeNRB)
                    .addComponent(PineappleNRB)
                    .addComponent(BananaNRB)
                    .addComponent(MangoNRB)
                    .addComponent(GrapefruitNRB))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrangeNRB)
                .addGap(27, 27, 27)
                .addComponent(PineappleNRB)
                .addGap(26, 26, 26)
                .addComponent(BananaNRB)
                .addGap(28, 28, 28)
                .addComponent(MangoNRB)
                .addGap(27, 27, 27)
                .addComponent(GrapefruitNRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(218, 192, 203));

        orangeButtonGroup.add(OrangeERB);

        PineappleButtonGroup.add(PineappleERB);

        bananaButtonGroup.add(BananaERB);

        strawberrybuttonGroup.add(MangoERB);
        MangoERB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangoERBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(GrapefruitERB);
        GrapefruitERB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrapefruitERBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrangeERB)
                    .addComponent(PineappleERB)
                    .addComponent(BananaERB)
                    .addComponent(MangoERB)
                    .addComponent(GrapefruitERB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OrangeERB)
                .addGap(27, 27, 27)
                .addComponent(PineappleERB)
                .addGap(26, 26, 26)
                .addComponent(BananaERB)
                .addGap(28, 28, 28)
                .addComponent(MangoERB)
                .addGap(28, 28, 28)
                .addComponent(GrapefruitERB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(218, 192, 203));

        strawberrybuttonGroup.add(strawberrySmallRadioButton);
        strawberrySmallRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberrySmallRadioButtonActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(AppleSmallRadioButton1);
        AppleSmallRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleSmallRadioButton1ActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(WatermelonSmallRB);
        WatermelonSmallRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WatermelonSmallRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(BlueberrySRB);
        BlueberrySRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueberrySRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(DatesSRB);
        DatesSRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatesSRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(RoseberrySRB);
        RoseberrySRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoseberrySRBActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(218, 192, 203));

        strawberrybuttonGroup.add(strawberryNormalRadioButton14);
        strawberryNormalRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryNormalRadioButton14ActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(AppleNormalRadioButton15);
        AppleNormalRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleNormalRadioButton15ActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(WatermelonNormalRB);
        WatermelonNormalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WatermelonNormalRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(BlueberryNRB);
        BlueberryNRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueberryNRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(DatesNRB);
        DatesNRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatesNRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(RoseberryNRB);
        RoseberryNRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoseberryNRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strawberryNormalRadioButton14)
                    .addComponent(AppleNormalRadioButton15)
                    .addComponent(WatermelonNormalRB)
                    .addComponent(BlueberryNRB)
                    .addComponent(DatesNRB)
                    .addComponent(RoseberryNRB))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(strawberryNormalRadioButton14)
                .addGap(18, 18, 18)
                .addComponent(AppleNormalRadioButton15)
                .addGap(29, 29, 29)
                .addComponent(WatermelonNormalRB)
                .addGap(27, 27, 27)
                .addComponent(BlueberryNRB)
                .addGap(32, 32, 32)
                .addComponent(DatesNRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RoseberryNRB)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strawberrySmallRadioButton)
                    .addComponent(AppleSmallRadioButton1)
                    .addComponent(WatermelonSmallRB)
                    .addComponent(BlueberrySRB)
                    .addComponent(DatesSRB)
                    .addComponent(RoseberrySRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(strawberrySmallRadioButton)
                .addGap(18, 18, 18)
                .addComponent(AppleSmallRadioButton1)
                .addGap(29, 29, 29)
                .addComponent(WatermelonSmallRB)
                .addGap(27, 27, 27)
                .addComponent(BlueberrySRB)
                .addGap(32, 32, 32)
                .addComponent(DatesSRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(RoseberrySRB)
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(218, 192, 203));

        strawberrybuttonGroup.add(strawberryExtraRadioButton20);
        strawberryExtraRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryExtraRadioButton20ActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(AppleExtraRB);
        AppleExtraRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleExtraRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(WatermelonExtraRB);
        WatermelonExtraRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WatermelonExtraRBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(BlueberryERB);
        BlueberryERB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueberryERBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(DatesERB);
        DatesERB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatesERBActionPerformed(evt);
            }
        });

        strawberrybuttonGroup.add(RoseberryERB);
        RoseberryERB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoseberryERBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strawberryExtraRadioButton20)
                    .addComponent(AppleExtraRB)
                    .addComponent(WatermelonExtraRB)
                    .addComponent(BlueberryERB)
                    .addComponent(DatesERB)
                    .addComponent(RoseberryERB))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(strawberryExtraRadioButton20)
                .addGap(18, 18, 18)
                .addComponent(AppleExtraRB)
                .addGap(29, 29, 29)
                .addComponent(WatermelonExtraRB)
                .addGap(27, 27, 27)
                .addComponent(BlueberryERB)
                .addGap(32, 32, 32)
                .addComponent(DatesERB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(RoseberryERB)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(218, 192, 203));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/orange.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/pineapple.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/banana.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/mango.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/grapefruit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(218, 192, 203));

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 51));
        jLabel24.setText("Pineapple");

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 51));
        jLabel23.setText("Orange");

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setText("Banana");

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 51));
        jLabel27.setText("Mango");

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 51));
        jLabel26.setText("Grapefruit");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23)
                .addGap(27, 27, 27)
                .addComponent(jLabel24)
                .addGap(28, 28, 28)
                .addComponent(jLabel25)
                .addGap(28, 28, 28)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(19, 19, 19))
        );

        jButton1.setBackground(new java.awt.Color(236, 80, 148));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clrear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(924, 924, 924)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton28))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton26))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton34))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jRadioButton23))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton24)
                            .addGap(30, 30, 30)
                            .addComponent(jRadioButton20))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jToggleButton1)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton24)
                            .addComponent(jRadioButton20))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton34)
                            .addComponent(jRadioButton35))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton30)
                            .addComponent(jRadioButton26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton29)
                            .addComponent(jRadioButton28))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton35ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LiquidsGUI liquid=new LiquidsGUI();
        
        if(strawberrySmallRadioButton.isSelected())
            try {
                blender.addIngredient(new Strawberry(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(strawberryNormalRadioButton14.isSelected())
        {
            try {
                blender.addIngredient(new Strawberry(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(strawberryExtraRadioButton20.isSelected())
        {
            try {
                blender.addIngredient(new Strawberry(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(AppleSmallRadioButton1.isSelected())
            try {
                blender.addIngredient(new Apple(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(AppleNormalRadioButton15.isSelected())
        {
            try {
                blender.addIngredient(new Apple(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(AppleExtraRB.isSelected())
        {
            try {
                blender.addIngredient(new Apple(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
         else if(WatermelonSmallRB.isSelected())
            try {
                blender.addIngredient(new Watermelon(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(WatermelonNormalRB.isSelected())
        {
            try {
                blender.addIngredient(new Watermelon(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(WatermelonExtraRB.isSelected())
        {
            try {
                blender.addIngredient(new Watermelon(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(BlueberrySRB.isSelected())
            try {
                blender.addIngredient(new Blueberry(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(BlueberryNRB.isSelected())
        {
            try {
                blender.addIngredient(new Blueberry(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(BlueberryERB.isSelected())
        {
            try {
                blender.addIngredient(new Blueberry(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(DatesSRB.isSelected())
            try {
                blender.addIngredient(new Dates(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(DatesNRB.isSelected())
        {
            try {
                blender.addIngredient(new Dates(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(DatesERB.isSelected())
        {
            try {
                blender.addIngredient(new Dates(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
         else if(RoseberrySRB.isSelected())
            try {
                blender.addIngredient(new Roseberry(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(RoseberryNRB.isSelected())
        {
            try {
                blender.addIngredient(new Roseberry(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(RoseberryERB.isSelected())
        {
            try {
                blender.addIngredient(new Roseberry(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(OrangeSRB.isSelected())
            try {
                blender.addIngredient(new Orange(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(OrangeNRB.isSelected())
        {
            try {
                blender.addIngredient(new Orange(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(OrangeERB.isSelected())
        {
            try {
                blender.addIngredient(new Orange(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(OrangeSRB.isSelected())
            try {
                blender.addIngredient(new Orange(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        else if(OrangeNRB.isSelected())
        {
            try {
                blender.addIngredient(new Orange(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(OrangeERB.isSelected())
        {
            try {
                blender.addIngredient(new Orange(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
        
            
            
            
            
            
            
            //Showing the next frame 
        liquid.show();
        dispose();
        System.out.println(blender.getInfo());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void strawberrySmallRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberrySmallRadioButtonActionPerformed
        try {
            
            blender.addIngredient(new Strawberry(1));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_strawberrySmallRadioButtonActionPerformed

    private void AppleSmallRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleSmallRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppleSmallRadioButton1ActionPerformed

    private void DatesSRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatesSRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatesSRBActionPerformed

    private void BlueberrySRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueberrySRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlueberrySRBActionPerformed

    private void GrapefruitSRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrapefruitSRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrapefruitSRBActionPerformed

    private void MangoSRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangoSRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MangoSRBActionPerformed

    private void RoseberrySRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoseberrySRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoseberrySRBActionPerformed

    private void WatermelonSmallRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatermelonSmallRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WatermelonSmallRBActionPerformed

    private void strawberryNormalRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryNormalRadioButton14ActionPerformed
        // TODO add your handling code here:
        try {
            
            blender.addIngredient(new Strawberry(2));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_strawberryNormalRadioButton14ActionPerformed

    private void AppleNormalRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleNormalRadioButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppleNormalRadioButton15ActionPerformed

    private void WatermelonNormalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatermelonNormalRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WatermelonNormalRBActionPerformed

    private void BlueberryNRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueberryNRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlueberryNRBActionPerformed

    private void DatesNRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatesNRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatesNRBActionPerformed

    private void RoseberryNRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoseberryNRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoseberryNRBActionPerformed

    private void strawberryExtraRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryExtraRadioButton20ActionPerformed
        // TODO add your handling code here:
        try {
            
            blender.addIngredient(new Strawberry(3));
        } catch (BlenderOverFlowException ex) {
            Logger.getLogger(FruitsMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_strawberryExtraRadioButton20ActionPerformed

    private void AppleExtraRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleExtraRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppleExtraRBActionPerformed

    private void WatermelonExtraRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatermelonExtraRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WatermelonExtraRBActionPerformed

    private void BlueberryERBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueberryERBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlueberryERBActionPerformed

    private void DatesERBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatesERBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatesERBActionPerformed

    private void RoseberryERBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoseberryERBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoseberryERBActionPerformed

    private void MangoNRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangoNRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MangoNRBActionPerformed

    private void GrapefruitNRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrapefruitNRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrapefruitNRBActionPerformed

    private void MangoERBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangoERBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MangoERBActionPerformed

    private void GrapefruitERBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrapefruitERBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrapefruitERBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DatesSRB.setSelected(false);
        strawberrySmallRadioButton.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FruitsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FruitsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FruitsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FruitsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FruitsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AppleExtraRB;
    private javax.swing.JRadioButton AppleNormalRadioButton15;
    private javax.swing.JRadioButton AppleSmallRadioButton1;
    private javax.swing.JRadioButton BananaERB;
    private javax.swing.JRadioButton BananaNRB;
    private javax.swing.JRadioButton BananaSRB;
    private javax.swing.JRadioButton BlueberryERB;
    private javax.swing.JRadioButton BlueberryNRB;
    private javax.swing.JRadioButton BlueberrySRB;
    private javax.swing.JRadioButton DatesERB;
    private javax.swing.JRadioButton DatesNRB;
    private javax.swing.JRadioButton DatesSRB;
    private javax.swing.JRadioButton GrapefruitERB;
    private javax.swing.JRadioButton GrapefruitNRB;
    private javax.swing.JRadioButton GrapefruitSRB;
    private javax.swing.JRadioButton MangoERB;
    private javax.swing.JRadioButton MangoNRB;
    private javax.swing.JRadioButton MangoSRB;
    private javax.swing.JRadioButton OrangeERB;
    private javax.swing.JRadioButton OrangeNRB;
    private javax.swing.JRadioButton OrangeSRB;
    private javax.swing.ButtonGroup PineappleButtonGroup;
    private javax.swing.JRadioButton PineappleERB;
    private javax.swing.JRadioButton PineappleNRB;
    private javax.swing.JRadioButton PineappleSRB;
    private javax.swing.JRadioButton RoseberryERB;
    private javax.swing.JRadioButton RoseberryNRB;
    private javax.swing.JRadioButton RoseberrySRB;
    private javax.swing.JRadioButton WatermelonExtraRB;
    private javax.swing.JRadioButton WatermelonNormalRB;
    private javax.swing.JRadioButton WatermelonSmallRB;
    private javax.swing.ButtonGroup appleButtonGroup;
    private javax.swing.ButtonGroup bananaButtonGroup;
    private javax.swing.ButtonGroup blueberryButtonGroup;
    private javax.swing.ButtonGroup datesButtonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.ButtonGroup orangeButtonGroup;
    private javax.swing.JRadioButton strawberryExtraRadioButton20;
    private javax.swing.JRadioButton strawberryNormalRadioButton14;
    private javax.swing.JRadioButton strawberrySmallRadioButton;
    private javax.swing.ButtonGroup strawberrybuttonGroup;
    private javax.swing.ButtonGroup watermelonButtonGroup;
    // End of variables declaration//GEN-END:variables
}
