/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphical;

import containers.*;
import exceptions.BlenderOverFlowException;
import liquids.*;
import ingredients.Sugar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import toppings.*;

/**
 *
 * @author lenovo
 */
public class LiquidsGUI extends javax.swing.JFrame {
    private Blender blender;
    private boolean liquidFlag=false,cupFlag=false;
    /**
     * Creates new form LiquidsGUI
     */
    public LiquidsGUI() {
       
        initComponents();
    }
    public LiquidsGUI(Blender blender)
    {
        initComponents();
        this.blender=blender;
        liquidFlag=false;
        cupFlag=false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        liquidsButtonGroup = new javax.swing.ButtonGroup();
        cupsButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sugarjSlider = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        dairyMilkToggleButton = new javax.swing.JToggleButton();
        orangeJuiceToggleButton = new javax.swing.JToggleButton();
        oatMilkToggleButton = new javax.swing.JToggleButton();
        almondMilkToggleButton = new javax.swing.JToggleButton();
        lemonJuiceToggleButton = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sprinklesToggleButton = new javax.swing.JToggleButton();
        coconutFlakesToggleButton = new javax.swing.JToggleButton();
        caramelToggleButton = new javax.swing.JToggleButton();
        chocolateSauseToggleButton = new javax.swing.JToggleButton();
        whippedCreamToggleButton = new javax.swing.JToggleButton();
        CherryToggleButton = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();
        finishButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        smallCupToggleButton = new javax.swing.JToggleButton();
        mediumCupToggleButton = new javax.swing.JToggleButton();
        largeCupToggleButton = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 192, 203));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 80, 148));
        jLabel2.setText("Liquids Menu");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 66, 66));
        jLabel3.setText("Juice: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 66, 66));
        jLabel4.setText("Milk:");

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 80, 148));
        jLabel5.setText("Sugar");

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 80, 148));
        jLabel6.setText("Toppings");

        sugarjSlider.setMajorTickSpacing(1);
        sugarjSlider.setMaximum(10);
        sugarjSlider.setMinorTickSpacing(1);
        sugarjSlider.setPaintLabels(true);
        sugarjSlider.setPaintTicks(true);
        sugarjSlider.setToolTipText("");
        sugarjSlider.setValue(0);
        sugarjSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sugarjSlider.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sugarjSliderAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sugarjSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sugarjSliderMouseDragged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 80, 148));
        jLabel7.setText("Cup Size:");

        dairyMilkToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(dairyMilkToggleButton);
        dairyMilkToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        dairyMilkToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        dairyMilkToggleButton.setText("Dairy Milk");
        dairyMilkToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dairyMilkToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dairyMilkToggleButtonActionPerformed(evt);
            }
        });

        orangeJuiceToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(orangeJuiceToggleButton);
        orangeJuiceToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        orangeJuiceToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        orangeJuiceToggleButton.setText("Orange Juice");
        orangeJuiceToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orangeJuiceToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeJuiceToggleButtonActionPerformed(evt);
            }
        });

        oatMilkToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(oatMilkToggleButton);
        oatMilkToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        oatMilkToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        oatMilkToggleButton.setText("Oat Milk");
        oatMilkToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oatMilkToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oatMilkToggleButtonActionPerformed(evt);
            }
        });

        almondMilkToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(almondMilkToggleButton);
        almondMilkToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        almondMilkToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        almondMilkToggleButton.setText("Almond Milk");
        almondMilkToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        almondMilkToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almondMilkToggleButtonActionPerformed(evt);
            }
        });

        lemonJuiceToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(lemonJuiceToggleButton);
        lemonJuiceToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lemonJuiceToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        lemonJuiceToggleButton.setText("Lemon Juice");
        lemonJuiceToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lemonJuiceToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonJuiceToggleButtonActionPerformed(evt);
            }
        });

        sprinklesToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        sprinklesToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        sprinklesToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        sprinklesToggleButton.setText("Sprinkles");
        sprinklesToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sprinklesToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinklesToggleButtonActionPerformed(evt);
            }
        });

        coconutFlakesToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        coconutFlakesToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        coconutFlakesToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        coconutFlakesToggleButton.setText("Coconut Flakes");
        coconutFlakesToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coconutFlakesToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coconutFlakesToggleButtonActionPerformed(evt);
            }
        });

        caramelToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        caramelToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        caramelToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        caramelToggleButton.setText("Caramel");
        caramelToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caramelToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramelToggleButtonActionPerformed(evt);
            }
        });

        chocolateSauseToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        chocolateSauseToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        chocolateSauseToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        chocolateSauseToggleButton.setText("Chocolate Sause");
        chocolateSauseToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chocolateSauseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateSauseToggleButtonActionPerformed(evt);
            }
        });

        whippedCreamToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        whippedCreamToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        whippedCreamToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        whippedCreamToggleButton.setText("Whipped Cream");
        whippedCreamToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        whippedCreamToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whippedCreamToggleButtonActionPerformed(evt);
            }
        });

        CherryToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        CherryToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CherryToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        CherryToggleButton.setText("Cherry");
        CherryToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CherryToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CherryToggleButtonActionPerformed(evt);
            }
        });

        finishButton.setBackground(new java.awt.Color(236, 80, 148));
        finishButton.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        finishButton.setForeground(new java.awt.Color(218, 192, 203));
        finishButton.setText("Finish");
        finishButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 80, 148), 5, true));
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        smallCupToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        cupsButtonGroup.add(smallCupToggleButton);
        smallCupToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        smallCupToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        smallCupToggleButton.setText("Small Cup");
        smallCupToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        smallCupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallCupToggleButtonActionPerformed(evt);
            }
        });

        mediumCupToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        cupsButtonGroup.add(mediumCupToggleButton);
        mediumCupToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mediumCupToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        mediumCupToggleButton.setText("Medium Cup");
        mediumCupToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumCupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCupToggleButtonActionPerformed(evt);
            }
        });

        largeCupToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        cupsButtonGroup.add(largeCupToggleButton);
        largeCupToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        largeCupToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        largeCupToggleButton.setText("Large Cup");
        largeCupToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        largeCupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeCupToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator4)
                        .addComponent(jSeparator3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(sugarjSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dairyMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oatMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(almondMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(134, 134, 134)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lemonJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orangeJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coconutFlakesToggleButton)
                                    .addComponent(sprinklesToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(smallCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chocolateSauseToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(caramelToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CherryToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(whippedCreamToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mediumCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(largeCupToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dairyMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oatMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(almondMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lemonJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orangeJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sugarjSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sprinklesToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chocolateSauseToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whippedCreamToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coconutFlakesToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caramelToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CherryToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largeCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void whippedCreamToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whippedCreamToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whippedCreamToggleButtonActionPerformed

    private void lemonJuiceToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonJuiceToggleButtonActionPerformed

        liquidFlag=true;
// TODO add your handling code here:
    }//GEN-LAST:event_lemonJuiceToggleButtonActionPerformed

    private void sugarjSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sugarjSliderMouseDragged
 cupFlag=true;
       finishButton.setEnabled(cupFlag);        
// TODO add your handling code here:
    }//GEN-LAST:event_sugarjSliderMouseDragged

    private void sugarjSliderAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sugarjSliderAncestorAdded
         cupFlag=true;
        finishButton.setEnabled(cupFlag);
        // TODO add your handling code here:
    }//GEN-LAST:event_sugarjSliderAncestorAdded

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        int sugar;
        blender=new Blender();
            if (!liquidFlag)
                JOptionPane.showMessageDialog(this,"You must choose atleast one of the liquids","Warning",JOptionPane.ERROR_MESSAGE);
            
           if (!cupFlag) 
            JOptionPane.showMessageDialog(this, "You must choose a Cup Size","Warning",JOptionPane.ERROR_MESSAGE);
        
     
        
        
        try{
            if (dairyMilkToggleButton.isSelected())
                blender.addIngredient(new DairyMilk());
            
            else if (oatMilkToggleButton.isSelected())
                blender.addIngredient(new OatMilk());
            
            else if (orangeJuiceToggleButton.isSelected())
                blender.addIngredient(new OrangeJuice());
            
            else if (lemonJuiceToggleButton.isSelected())
                blender.addIngredient(new LemonJuice());
            
            else if (almondMilkToggleButton.isSelected())
                blender.addIngredient(new AlmondMilk());
            
            sugar=sugarjSlider.getValue();
            System.out.println(sugar);
            blender.addIngredient(new Sugar(sugar));
            
            if(sprinklesToggleButton.isSelected())
                blender.addIngredient(new Sprinkles());
            
            if(caramelToggleButton.isSelected())
                blender.addIngredient(new Caramel());
            
            if(chocolateSauseToggleButton.isSelected())
                blender.addIngredient(new ChocolateSause());
            
            if(whippedCreamToggleButton.isSelected())
                blender.addIngredient(new WhippedCream());
            
            if(coconutFlakesToggleButton.isSelected())
                blender.addIngredient(new CoconutFlakes());
            
            if(CherryToggleButton.isSelected())
                blender.addIngredient(new Cherry());
            
            // cups  
            Cup cup=null;
            if (smallCupToggleButton.isSelected()){
                double numberOfCups=  blender.getCocktailVolume() / SmallCup.getCupCapacity();
                cup=new SmallCup(numberOfCups);
                try {
                    blender.pour(cup);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
//Logger.getLogger(LiquidsGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            else if (mediumCupToggleButton.isSelected())
            {
                 double numberOfCups=  blender.getCocktailVolume() / MediumCup.getCupCapacity();
                 cup=new MediumCup(numberOfCups);

                try {
                    blender.pour(cup);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    //Logger.getLogger(LiquidsGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            else if (largeCupToggleButton.isSelected())
            {
                 double numberOfCups=  blender.getCocktailVolume() / LargeCup.getCupCapacity();
                 cup=new LargeCup(numberOfCups);
                try {
                    blender.pour(cup);
                } 
                catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    //Logger.getLogger(LiquidsGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  
            
            else{
                JOptionPane.showMessageDialog(this, "You must choose a Cup Size","Warning",JOptionPane.ERROR_MESSAGE);
            }
            if (cup!=null){
            
                ResultOwnDrink result=new ResultOwnDrink(blender, cup);
                result.show();
                dispose();   
                
            }
        }
        catch (BlenderOverFlowException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
//        catch(Exception e)
//        {
//            JOptionPane.showMessageDialog(this, "another exception");
//            
//        }
      
    }//GEN-LAST:event_finishButtonActionPerformed

    private void dairyMilkToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dairyMilkToggleButtonActionPerformed
       liquidFlag=true;
            // TODO add your handling code here:
    }//GEN-LAST:event_dairyMilkToggleButtonActionPerformed

    private void oatMilkToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oatMilkToggleButtonActionPerformed
        liquidFlag=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_oatMilkToggleButtonActionPerformed

    private void almondMilkToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almondMilkToggleButtonActionPerformed
        liquidFlag=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_almondMilkToggleButtonActionPerformed

    private void orangeJuiceToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeJuiceToggleButtonActionPerformed
        liquidFlag=true;        
// TODO add your handling code here:
    }//GEN-LAST:event_orangeJuiceToggleButtonActionPerformed

    private void smallCupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallCupToggleButtonActionPerformed
        cupFlag=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_smallCupToggleButtonActionPerformed

    private void mediumCupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCupToggleButtonActionPerformed
    cupFlag=true;       
    // TODO add your handling code here:
    }//GEN-LAST:event_mediumCupToggleButtonActionPerformed

    private void largeCupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeCupToggleButtonActionPerformed
        cupFlag=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_largeCupToggleButtonActionPerformed

    private void sprinklesToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinklesToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sprinklesToggleButtonActionPerformed

    private void chocolateSauseToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateSauseToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chocolateSauseToggleButtonActionPerformed

    private void coconutFlakesToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coconutFlakesToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coconutFlakesToggleButtonActionPerformed

    private void caramelToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramelToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caramelToggleButtonActionPerformed

    private void CherryToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CherryToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CherryToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiquidsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CherryToggleButton;
    private javax.swing.JToggleButton almondMilkToggleButton;
    private javax.swing.JToggleButton caramelToggleButton;
    private javax.swing.JToggleButton chocolateSauseToggleButton;
    private javax.swing.JToggleButton coconutFlakesToggleButton;
    private javax.swing.ButtonGroup cupsButtonGroup;
    private javax.swing.JToggleButton dairyMilkToggleButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton largeCupToggleButton;
    private javax.swing.JToggleButton lemonJuiceToggleButton;
    private javax.swing.ButtonGroup liquidsButtonGroup;
    private javax.swing.JToggleButton mediumCupToggleButton;
    private javax.swing.JToggleButton oatMilkToggleButton;
    private javax.swing.JToggleButton orangeJuiceToggleButton;
    private javax.swing.JToggleButton smallCupToggleButton;
    private javax.swing.JToggleButton sprinklesToggleButton;
    private javax.swing.JSlider sugarjSlider;
    private javax.swing.JToggleButton whippedCreamToggleButton;
    // End of variables declaration//GEN-END:variables
}
