/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphical;

/**
 *
 * @author lenovo
 */
public class LiquidsGUI extends javax.swing.JFrame {

    /**
     * Creates new form LiquidsGUI
     */
    public LiquidsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        liquids = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dairyMilkButton = new javax.swing.JButton();
        lemonJuiceButton = new javax.swing.JButton();
        almondMilkButton = new javax.swing.JButton();
        oatMilkButton = new javax.swing.JButton();
        orangeJuiceButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        whippedCreamButton = new javax.swing.JButton();
        cherryButton = new javax.swing.JButton();
        chocolateSauseButton = new javax.swing.JButton();
        caramelButton = new javax.swing.JButton();
        coconutFlakesButton = new javax.swing.JButton();
        sprinklesButton = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        mediumCupButton = new javax.swing.JButton();
        LargeCupButton = new javax.swing.JButton();
        smallCupButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 192, 203));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 80, 148));
        jLabel2.setText("Liquids Menu");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 66, 66));
        jLabel3.setText("Juice: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 66, 66));
        jLabel4.setText("Milk:");

        dairyMilkButton.setBackground(new java.awt.Color(218, 192, 203));
        dairyMilkButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        dairyMilkButton.setForeground(new java.awt.Color(69, 66, 66));
        dairyMilkButton.setText("• Dairy Milk");
        dairyMilkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(dairyMilkButton);
        dairyMilkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dairyMilkButtonActionPerformed(evt);
            }
        });

        lemonJuiceButton.setBackground(new java.awt.Color(218, 192, 203));
        lemonJuiceButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lemonJuiceButton.setForeground(new java.awt.Color(69, 66, 66));
        lemonJuiceButton.setText("• Lemon Milk");
        lemonJuiceButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(lemonJuiceButton);
        lemonJuiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonJuiceButtonActionPerformed(evt);
            }
        });

        almondMilkButton.setBackground(new java.awt.Color(218, 192, 203));
        almondMilkButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        almondMilkButton.setForeground(new java.awt.Color(69, 66, 66));
        almondMilkButton.setText("• Almond Milk");
        almondMilkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(almondMilkButton);
        almondMilkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almondMilkButtonActionPerformed(evt);
            }
        });

        oatMilkButton.setBackground(new java.awt.Color(218, 192, 203));
        oatMilkButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        oatMilkButton.setForeground(new java.awt.Color(69, 66, 66));
        oatMilkButton.setText("• Oat Milk");
        oatMilkButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(oatMilkButton);
        oatMilkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oatMilkButtonActionPerformed(evt);
            }
        });

        orangeJuiceButton.setBackground(new java.awt.Color(218, 192, 203));
        orangeJuiceButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        orangeJuiceButton.setForeground(new java.awt.Color(69, 66, 66));
        orangeJuiceButton.setText("• Orange Juice");
        orangeJuiceButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(orangeJuiceButton);
        orangeJuiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeJuiceButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 80, 148));
        jLabel5.setText("Sugar");

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 80, 148));
        jLabel6.setText("Toppings");

        whippedCreamButton.setBackground(new java.awt.Color(218, 192, 203));
        whippedCreamButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        whippedCreamButton.setForeground(new java.awt.Color(69, 66, 66));
        whippedCreamButton.setText("• Whipped Cream");
        whippedCreamButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        whippedCreamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whippedCreamButtonActionPerformed(evt);
            }
        });

        cherryButton.setBackground(new java.awt.Color(218, 192, 203));
        cherryButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        cherryButton.setForeground(new java.awt.Color(69, 66, 66));
        cherryButton.setText("• Cherry");
        cherryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cherryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherryButtonActionPerformed(evt);
            }
        });

        chocolateSauseButton.setBackground(new java.awt.Color(218, 192, 203));
        chocolateSauseButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        chocolateSauseButton.setForeground(new java.awt.Color(69, 66, 66));
        chocolateSauseButton.setText("• Chocolate Sauce");
        chocolateSauseButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chocolateSauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateSauseButtonActionPerformed(evt);
            }
        });

        caramelButton.setBackground(new java.awt.Color(218, 192, 203));
        caramelButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        caramelButton.setForeground(new java.awt.Color(69, 66, 66));
        caramelButton.setText("• Caramel");
        caramelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caramelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramelButtonActionPerformed(evt);
            }
        });

        coconutFlakesButton.setBackground(new java.awt.Color(218, 192, 203));
        coconutFlakesButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        coconutFlakesButton.setForeground(new java.awt.Color(69, 66, 66));
        coconutFlakesButton.setText("• Coconut Flakes");
        coconutFlakesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coconutFlakesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coconutFlakesButtonActionPerformed(evt);
            }
        });

        sprinklesButton.setBackground(new java.awt.Color(218, 192, 203));
        sprinklesButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        sprinklesButton.setForeground(new java.awt.Color(69, 66, 66));
        sprinklesButton.setText("• Sprinkles");
        sprinklesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sprinklesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinklesButtonActionPerformed(evt);
            }
        });

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(10);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(1);
        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSlider1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 80, 148));
        jLabel7.setText("Cup Size:");

        mediumCupButton.setBackground(new java.awt.Color(218, 192, 203));
        mediumCupButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mediumCupButton.setForeground(new java.awt.Color(69, 66, 66));
        mediumCupButton.setText("• Medium Cup");
        mediumCupButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(mediumCupButton);
        mediumCupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCupButtonActionPerformed(evt);
            }
        });

        LargeCupButton.setBackground(new java.awt.Color(218, 192, 203));
        LargeCupButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        LargeCupButton.setForeground(new java.awt.Color(69, 66, 66));
        LargeCupButton.setText("• Large Cup");
        LargeCupButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(LargeCupButton);
        LargeCupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargeCupButtonActionPerformed(evt);
            }
        });

        smallCupButton.setBackground(new java.awt.Color(218, 192, 203));
        smallCupButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        smallCupButton.setForeground(new java.awt.Color(69, 66, 66));
        smallCupButton.setText("• Small Cup");
        smallCupButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liquids.add(smallCupButton);
        smallCupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallCupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(almondMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dairyMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oatMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lemonJuiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orangeJuiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(whippedCreamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cherryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(chocolateSauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(caramelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(coconutFlakesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sprinklesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(smallCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mediumCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LargeCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(orangeJuiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lemonJuiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dairyMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(almondMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oatMilkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whippedCreamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chocolateSauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coconutFlakesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caramelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprinklesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cherryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LargeCupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dairyMilkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dairyMilkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dairyMilkButtonActionPerformed

    private void lemonJuiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonJuiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemonJuiceButtonActionPerformed

    private void almondMilkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almondMilkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almondMilkButtonActionPerformed

    private void oatMilkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oatMilkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oatMilkButtonActionPerformed

    private void orangeJuiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeJuiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeJuiceButtonActionPerformed

    private void whippedCreamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whippedCreamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whippedCreamButtonActionPerformed

    private void cherryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cherryButtonActionPerformed

    private void chocolateSauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateSauseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chocolateSauseButtonActionPerformed

    private void caramelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caramelButtonActionPerformed

    private void coconutFlakesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coconutFlakesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coconutFlakesButtonActionPerformed

    private void sprinklesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinklesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sprinklesButtonActionPerformed

    private void mediumCupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumCupButtonActionPerformed

    private void LargeCupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargeCupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LargeCupButtonActionPerformed

    private void smallCupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallCupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallCupButtonActionPerformed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1MouseDragged

    private void jSlider1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSlider1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiquidsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiquidsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LargeCupButton;
    private javax.swing.JButton almondMilkButton;
    private javax.swing.JButton caramelButton;
    private javax.swing.JButton cherryButton;
    private javax.swing.JButton chocolateSauseButton;
    private javax.swing.JButton coconutFlakesButton;
    private javax.swing.JButton dairyMilkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton lemonJuiceButton;
    private javax.swing.ButtonGroup liquids;
    private javax.swing.JButton mediumCupButton;
    private javax.swing.JButton oatMilkButton;
    private javax.swing.JButton orangeJuiceButton;
    private javax.swing.JButton smallCupButton;
    private javax.swing.JButton sprinklesButton;
    private javax.swing.JButton whippedCreamButton;
    // End of variables declaration//GEN-END:variables
}
